FROM centos:latest


MAINTAINER LMO lmo@lmo.com

WORKDIR gitserver

RUN set -x \
    && yum groupinstall "Development Tools" \
    && yum install gettext-devel openssl-devel perl-CPAN perl-devel zlib-devel \
    && yum -y install net-tools \
    && yum install -y git


